resource_types:
  - name: resource
    type: docker-image
    source:
      repository: mhd999/resource
      tag: dev

resources:
  - name: concource
    type: git
    source:
      uri: git@github.com:mhd999/concourse.git
      branch: master

  - name: resource-template
    type: resource
    source:
      source1: foo
      source2: bar

groups:
  - name: Master
    jobs:
    - test


jobs:
- name: test
  plan:
    - get: concourse
      trigger: true
      version: every

    - task: zip-and-upload
      file: concourse/task.yml

    - put: resource-template
      params: { param1: "hello jeff", param2: "How are you?" }